import { SectorType, QualityTier, StockFairValue } from './types';

export interface RawStockProfile {
    symbol: string;
    name: string;
    sector: string;
    sectorType: SectorType;
    defaultPrice: number;
    defaultPeak52w: number;
    targetWeight: number;
    currentWeight: number;

    pe: number;
    historicalPe: number; // 3-5y median
    pb: number;
    historicalPb: number; // 3-5y median

    epsGrowth: number; // % yoy
    roe: number; // %
    qualityScore: number; // 0-100
    qualityTier: QualityTier;

    fairValue: StockFairValue;

    sectorKeyMetricLabel: string;
    sectorKeyMetricValue: string;

    highlights: string[];
    risks: string[];
}

export const STOCK_PROFILES: RawStockProfile[] = [
    {
        symbol: 'FPT',
        name: 'Công ty Cổ phần FPT',
        sector: 'Công nghệ thông tin',
        sectorType: 'TECH',
        defaultPrice: 135000,
        defaultPeak52w: 160000,
        targetWeight: 12,
        currentWeight: 11,
        pe: 22.5,
        historicalPe: 23.5,
        pb: 5.8,
        historicalPb: 5.4,
        epsGrowth: 21.5,
        roe: 26.8,
        qualityScore: 92,
        qualityTier: 'A+',
        fairValue: {
            bear: 125000,
            base: 155000,
            bull: 175000,
        },
        sectorKeyMetricLabel: 'P/E & Tăng trưởng FCF / Doanh thu DX',
        sectorKeyMetricValue: 'Tăng trưởng đơn hàng chuyển đổi số +28% YoY',
        highlights: [
            'Doanh thu phần mềm nước ngoài duy trì tăng trưởng >20% ổn định',
            'ROE đạt 26.8%, biên lợi nhuận ròng bền vững qua nhiều chu kỳ',
            'Vị thế độc tôn trong xuất khẩu phần mềm & AI ecosystem tại Việt Nam',
        ],
        risks: [
            'Định giá P/E trên 20x yêu cầu mức tăng trưởng EPS cao liên tục',
            'Rủi ro biến động tỷ giá JPY (thị trường Nhật Bản chiếm tỷ trọng lớn)',
        ],
    },
    {
        symbol: 'HPG',
        name: 'Tập đoàn Hòa Phát',
        sector: 'Thép & Vật liệu xây dựng',
        sectorType: 'STEEL',
        defaultPrice: 26500,
        defaultPeak52w: 32000,
        targetWeight: 10,
        currentWeight: 8,
        pe: 11.2,
        historicalPe: 13.0,
        pb: 1.35,
        historicalPb: 1.65,
        epsGrowth: 32.0,
        roe: 14.5,
        qualityScore: 84,
        qualityTier: 'A',
        fairValue: {
            bear: 24000,
            base: 32500,
            bull: 38000,
        },
        sectorKeyMetricLabel: 'P/B & Chu kỳ Dung Quất 2',
        sectorKeyMetricValue: 'P/B 1.35x (Rẻ hơn TB 5 năm 1.65x), Dung Quất 2 vận hành',
        highlights: [
            'Dung Quất 2 chạy thương mại nâng công suất HRC thêm 5.6 triệu tấn/năm',
            'Chi phí sản xuất phôi thép thấp nhất khu vực, bảng cân đối lành mạnh',
            'P/B ở mức 1.35x chiết khấu đáng kể so với trung bình chu kỳ',
        ],
        risks: [
            'Áp lực thép giá rẻ từ Trung Quốc và diễn biến giá quặng sắt/than cốc',
            'Tốc độ phục hồi của thị trường bất động sản nội địa',
        ],
    },
    {
        symbol: 'TCB',
        name: 'Ngân hàng Techcombank',
        sector: 'Ngân hàng',
        sectorType: 'BANK',
        defaultPrice: 23500,
        defaultPeak52w: 26800,
        targetWeight: 10,
        currentWeight: 9,
        pe: 6.8,
        historicalPe: 8.5,
        pb: 1.05,
        historicalPb: 1.35,
        epsGrowth: 18.5,
        roe: 16.8,
        qualityScore: 88,
        qualityTier: 'A',
        fairValue: {
            bear: 21500,
            base: 28500,
            bull: 33000,
        },
        sectorKeyMetricLabel: 'P/B & Tỷ lệ CAR / CASA',
        sectorKeyMetricValue: 'CAR ~15.2% (Top 1), CASA phục hồi >40%',
        highlights: [
            'Hệ số an toàn vốn CAR vượt 15%, dẫn đầu toàn hệ thống ngân hàng',
            'Định giá P/B quanh 1.05x là mức rất hấp dẫn cho ngân hàng hiệu quả cao',
            'Nguồn thu phí dịch vụ & bảo hiểm/ngân hàng bán lẻ đa dạng',
        ],
        risks: [
            'Tỷ trọng cho vay và trái phiếu bất động sản cao hơn bình quân ngành',
            'NIM chịu áp lực cạnh tranh lãi suất cho vay mua nhà',
        ],
    },
    {
        symbol: 'MBB',
        name: 'Ngân hàng TMCP Quân Đội',
        sector: 'Ngân hàng',
        sectorType: 'BANK',
        defaultPrice: 24000,
        defaultPeak52w: 27500,
        targetWeight: 9,
        currentWeight: 9.5,
        pe: 5.9,
        historicalPe: 7.2,
        pb: 1.12,
        historicalPb: 1.30,
        epsGrowth: 15.2,
        roe: 21.4,
        qualityScore: 86,
        qualityTier: 'A',
        fairValue: {
            bear: 22000,
            base: 29000,
            bull: 33500,
        },
        sectorKeyMetricLabel: 'P/B & Chi phí vốn CASA',
        sectorKeyMetricValue: 'ROE >21%, P/E 5.9x cực rẻ, CASA vững mạnh',
        highlights: [
            'Lợi thế chi phí vốn thấp nhờ tiền gửi không kỳ hạn CASA quân đội/doanh nghiệp',
            'ROE liên tục duy trì trên 20%, tăng trưởng tín dụng hạn mức cao',
            'Hệ sinh thái tài chính trọn gói: bảo hiểm MIC/MB Ageas, chứng khoán MBS',
        ],
        risks: [
            'Nợ xấu nhóm bán lẻ và tài chính tiêu dùng MCredit cần kiểm soát chặt',
            'Khoản nợ tái cơ cấu một số tập đoàn năng lượng/BĐS',
        ],
    },
    {
        symbol: 'ACB',
        name: 'Ngân hàng TMCP Á Châu',
        sector: 'Ngân hàng',
        sectorType: 'BANK',
        defaultPrice: 25000,
        defaultPeak52w: 27800,
        targetWeight: 9,
        currentWeight: 8.5,
        pe: 6.5,
        historicalPe: 7.8,
        pb: 1.25,
        historicalPb: 1.45,
        epsGrowth: 14.0,
        roe: 22.8,
        qualityScore: 90,
        qualityTier: 'A+',
        fairValue: {
            bear: 23500,
            base: 30000,
            bull: 34000,
        },
        sectorKeyMetricLabel: 'P/B & Tỷ lệ nợ xấu NPL',
        sectorKeyMetricValue: 'NPL duy trì dưới 1.2%, không có rủi ro TPDN',
        highlights: [
            'Quản trị rủi ro hàng đầu hệ thống, danh mục sạch hầu như không có TPDN',
            'ROE đạt 22.8%, mô hình bán lẻ gia đình & SME truyền thống siêu bền bỉ',
            'Tỷ lệ bao phủ nợ xấu an toàn cao, cổ tức tiền mặt & cổ phiếu đều đặn',
        ],
        risks: [
            'Chiến lược thận trọng khiến tăng trưởng tín dụng có thể không đột biến',
            'Cạnh tranh khốc liệt mảng cho vay mua nhà và tiêu dùng',
        ],
    },
    {
        symbol: 'VPB',
        name: 'Ngân hàng VPBank',
        sector: 'Ngân hàng',
        sectorType: 'BANK',
        defaultPrice: 19500,
        defaultPeak52w: 22000,
        targetWeight: 8,
        currentWeight: 7.5,
        pe: 8.2,
        historicalPe: 9.5,
        pb: 0.98,
        historicalPb: 1.30,
        epsGrowth: 28.0,
        roe: 12.8,
        qualityScore: 78,
        qualityTier: 'B+',
        fairValue: {
            bear: 18000,
            base: 24500,
            bull: 28000,
        },
        sectorKeyMetricLabel: 'P/B & Vốn chủ sở hữu lớn nhất',
        sectorKeyMetricValue: 'P/B dưới 1.0x (0.98x), bộ đệm vốn SMBC dồi dào',
        highlights: [
            'Vốn chủ sở hữu lớn nhất nhóm ngân hàng tư nhân sau thương vụ SMBC',
            'P/B giảm xuống dưới giá trị sổ sách (0.98x), biên độ an toàn cao',
            'Kỳ vọng phục hồi tăng trưởng lợi nhuận mạnh mẽ từ FE Credit',
        ],
        risks: [
            'Tỷ lệ nợ xấu hợp nhất vẫn còn cao do mảng tín dụng tiêu dùng',
            'ROE tạm thời bị pha loãng sau đợt tăng vốn lớn',
        ],
    },
    {
        symbol: 'KDH',
        name: 'Nhà Khang Điền',
        sector: 'Bất động sản nhà ở',
        sectorType: 'REAL_ESTATE',
        defaultPrice: 32000,
        defaultPeak52w: 39000,
        targetWeight: 8,
        currentWeight: 6.5,
        pe: 22.0,
        historicalPe: 24.0,
        pb: 1.55,
        historicalPb: 1.85,
        epsGrowth: 19.5,
        roe: 8.2,
        qualityScore: 82,
        qualityTier: 'A',
        fairValue: {
            bear: 28000,
            base: 38500,
            bull: 44000,
        },
        sectorKeyMetricLabel: 'P/B & NAV Quỹ đất sạch TP.HCM',
        sectorKeyMetricValue: 'NAV ước tính 42,000đ/cp, hợp tác Keppel Land',
        highlights: [
            'Pháp lý dự án minh bạch nhất nhóm BĐS, sổ hồng trao tay khách hàng',
            'Quỹ đất rộng lớn tại TP.HCM (Privia, Clarita, Emeria hợp tác Keppel Land)',
            'Cơ cấu nợ vay an toàn, không có áp lực nợ trái phiếu quá hạn',
        ],
        risks: [
            'Tiến độ mở bán phụ thuộc sức cầu chung của thị trường BĐS căn hộ/nhà phố',
            'Vòng quay dự án kéo dài làm giảm ROE ngắn hạn',
        ],
    },
    {
        symbol: 'IDC',
        name: 'Tổng Công ty IDICO',
        sector: 'BĐS Khu công nghiệp',
        sectorType: 'INDUSTRIAL_PARK',
        defaultPrice: 56000,
        defaultPeak52w: 66000,
        targetWeight: 8,
        currentWeight: 8.5,
        pe: 9.8,
        historicalPe: 11.5,
        pb: 2.1,
        historicalPb: 2.5,
        epsGrowth: 22.4,
        roe: 24.5,
        qualityScore: 85,
        qualityTier: 'A',
        fairValue: {
            bear: 50000,
            base: 65000,
            bull: 74000,
        },
        sectorKeyMetricLabel: 'P/E & Diện tích đất KCN sẵn sàng cho thuê',
        sectorKeyMetricValue: 'Quỹ đất thương phẩm >600 ha, cổ tức tiền mặt 30-40%',
        highlights: [
            'Hưởng lợi trực tiếp từ dòng vốn FDI chuyển dịch vào Việt Nam',
            'Cổ tức tiền mặt đều đặn 3,000 - 4,000 đ/năm, dòng tiền thu trước lớn',
            'Quỹ đất tại Hựu Thạnh, Phú Mỹ 2, Cầu Nghìn có giá thuê tăng ổn định',
        ],
        risks: [
            'Pháp lý mở rộng KCN mới tại các địa phương mất nhiều thời gian',
            'Tình hình kinh tế toàn cầu có thể làm chậm quyết định thuê đất của đối tác FDI lớn',
        ],
    },
    {
        symbol: 'REE',
        name: 'Cơ Điện Lạnh REE',
        sector: 'Năng lượng & Cơ điện',
        sectorType: 'ENERGY_UTILITY',
        defaultPrice: 63000,
        defaultPeak52w: 72000,
        targetWeight: 8,
        currentWeight: 8.0,
        pe: 11.5,
        historicalPe: 12.8,
        pb: 1.35,
        historicalPb: 1.55,
        epsGrowth: 16.0,
        roe: 14.8,
        qualityScore: 88,
        qualityTier: 'A',
        fairValue: {
            bear: 58000,
            base: 73000,
            bull: 82000,
        },
        sectorKeyMetricLabel: 'P/E & Dòng tiền điện tái tạo / E-Town 6',
        sectorKeyMetricValue: 'E-Town 6 lấp đầy, danh mục thủy điện bước vào pha La Nina',
        highlights: [
            'Cỗ máy in tiền ổn định từ chuỗi thủy điện & năng lượng tái tạo',
            'Tòa nhà văn phòng E-Town 6 chuẩn LEED Platinum tăng doanh thu cho thuê',
            'Cơ cấu tài chính vững như bàn thạch, trả cổ tức bền bỉ hàng chục năm',
        ],
        risks: [
            'Thủy văn phụ thuộc chu kỳ thời tiết (El Nino/La Nina)',
            'Mảng M&E xây lắp phục hồi chậm do thị trường xây dựng thương mại',
        ],
    },
    {
        symbol: 'DBC',
        name: 'Tập đoàn DABACO',
        sector: 'Nông nghiệp & Chăn nuôi',
        sectorType: 'AGRICULTURE',
        defaultPrice: 28500,
        defaultPeak52w: 36000,
        targetWeight: 6,
        currentWeight: 5.0,
        pe: 9.5,
        historicalPe: 12.0,
        pb: 1.35,
        historicalPb: 1.60,
        epsGrowth: 45.0,
        roe: 15.2,
        qualityScore: 76,
        qualityTier: 'B+',
        fairValue: {
            bear: 25000,
            base: 35000,
            bull: 41000,
        },
        sectorKeyMetricLabel: 'P/E & Chu kỳ giá lợn hơi / Vaccine ASF',
        sectorKeyMetricValue: 'Biên LN gộp mở rộng theo giá heo, thương mại hóa vaccine ASF',
        highlights: [
            'Hưởng lợi chu kỳ giá lợn hơi hồi phục trong khi giá thức ăn chăn nuôi hạ nhiệt',
            'Kỳ vọng đột phá doanh thu từ thương mại hóa vaccine dịch tả lợn châu Phi (ASF)',
            'Mô hình khép kín 3F (Feed-Farm-Food) quy mô công nghiệp hàng đầu miền Bắc',
        ],
        risks: [
            'Tính chu kỳ ngành chăn nuôi rất cao, dịch bệnh bùng phát bất ngờ',
            'Biến động giá nguyên liệu nông sản thế giới (ngô, đậu tương)',
        ],
    },
    {
        symbol: 'SSI',
        name: 'Chứng khoán SSI',
        sector: 'Dịch vụ chứng khoán',
        sectorType: 'SECURITIES',
        defaultPrice: 32500,
        defaultPeak52w: 39500,
        targetWeight: 7,
        currentWeight: 7.0,
        pe: 14.5,
        historicalPe: 17.0,
        pb: 1.65,
        historicalPb: 2.10,
        epsGrowth: 26.5,
        roe: 13.5,
        qualityScore: 84,
        qualityTier: 'A',
        fairValue: {
            bear: 29000,
            base: 38500,
            bull: 45000,
        },
        sectorKeyMetricLabel: 'P/B & Quy mô Margin / Nâng hạng FTSE',
        sectorKeyMetricValue: 'P/B 1.65x (TB 5 năm 2.1x), dẫn đầu mảng Khách hàng tổ chức & Margin',
        highlights: [
            'Hưởng lợi trực tiếp lớn nhất khi triển khai hệ thống KRX & nâng hạng thị trường',
            'Thị phần môi giới và dư nợ cho vay margin top 2 thị trường, nguồn vốn dồi dào',
            'Định giá P/B 1.65x chiết khấu sâu so với mức trung bình 2.1x của các sóng tăng',
        ],
        risks: [
            'Thanh khoản thị trường biến động có thể ảnh hưởng doanh thu môi giới ngắn hạn',
            'Mảng tự doanh chịu rủi ro theo dao động chỉ số VN-Index',
        ],
    },
    {
        symbol: 'HDG',
        name: 'Tập đoàn Hà Đô',
        sector: 'Năng lượng & BĐS',
        sectorType: 'ENERGY_UTILITY',
        defaultPrice: 28000,
        defaultPeak52w: 35000,
        targetWeight: 5,
        currentWeight: 4.5,
        pe: 11.0,
        historicalPe: 13.5,
        pb: 1.15,
        historicalPb: 1.45,
        epsGrowth: 18.0,
        roe: 12.5,
        qualityScore: 75,
        qualityTier: 'B',
        fairValue: {
            bear: 25000,
            base: 34000,
            bull: 39000,
        },
        sectorKeyMetricLabel: 'P/B & Dòng tiền điện tái tạo + BĐS Charm Villas',
        sectorKeyMetricValue: 'Dòng tiền thủy điện/điện gió >1,000 tỷ/năm bù đắp cho BĐS',
        highlights: [
            'Dòng tiền ổn định từ 8 nhà máy thủy điện, điện mặt trời và điện gió',
            'Dự án BĐS Hado Charm Villas mở bán đợt cuối mang lại dòng tiền đột biến',
            'P/B quanh 1.15x ở vùng đáy lịch sử nhiều năm',
        ],
        risks: [
            'Thanh tra pháp lý một số dự án điện mặt trời/điện gió cần theo dõi kết luận',
            'Tiến độ triển khai các dự án BĐS mới chậm hơn kế hoạch',
        ],
    },
];

export const BENCHMARK_MARKET_DEFAULT = {
    vnIndex: 1285.5,
    peak52w: 1306.0,
    drawdown: -1.57,
    pe: 13.8,
    peHistorical5yAvg: 14.8,
    peHistorical5yMedian: 13.6,
    pb: 1.68,
    ma200: 1242.0,
    ma200Distance: 3.5,
    epsGrowth: 14.2,
};
